### ISSUE TITLE
TypeScript issues

### ISSUE THREAD

**Issue by philkunz** [fabiospampinato/watcher#33]
Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './enums.js'?
Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './watcher_handler.js'?
Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './watcher_locker.js'?
Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './watcher_poller.js'?

... and so on.

**Comment by fabiospampinato** [comment]
Maybe obvious, but how do I reproduce the issue? 🤔 Once compiled imported files seem to contain an extension already.

**Comment by benmccann** [comment]
@fabiospampinato if you do `npm install watcher` and then open up `node_modules/watcher/dist/types.d.ts` you'll see that the compiled output does not have file extensions:

![Screenshot from 2024-04-10 10-04-04](https://github.com/fabiospampinato/watcher/assets/322311/2df22e36-dcb2-4ea9-a06d-7af228db94b0)

With https://github.com/fabiospampinato/watcher/pull/38, the file extensions are present in the compiled output

**Comment by philkunz** [comment]
Here are the compiler options to reproduce this:

"compilerOptions": {
    "experimentalDecorators": true,
    "useDefineForClassFields": false,
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
    "verbatimModuleSyntax": true
  },

Until the fix is merged, there is a fixed version available at @tempfix/watcher, https://code.foss.global/tempfix/watcher

This error is present also in the dependencies of this package.

**Comment by SellersEvan** [comment]
Same issue here. I believe the extension name is required to be fully ESM compatible.

**Comment by benmccann** [comment]
Yeah, it sounds like it's a bug in tsex, which is used to package this library: https://github.com/fabiospampinato/tsex

**Comment by fabiospampinato** [comment]
I finally had the time to look into this, but it's going to take a little longer to fix it. A brain dump:

- [This commit](https://github.com/fabiospampinato/tsex/commit/ba98e9c6eb22750a2e4184de5aaa366d359cba99) in `tsex`, the convenience library I'm using to compile my npm packages, should make sure imports in `.d.ts` files get rewritten to have an extension too, which is basically the root problem here.
- There was an interesting comment in there though, that said: "// We don't actually want to fully resolve the path for declaration files", because I guess I had tried rewriting imports in declaration files already, but TS was complaining if I was importing from `.d.ts` files explicitly, but it wasn't complaining if I didn't specify the extension, so I just left those imports be. Apparently you need to say that you are importing from a `.js` file, then TS will resolve the `.d.ts` file by itself, you can't just tell it what the `.d.ts` file is, which doesn't make too much sense to me as far as "being explicit" goes, like it makes no sense to do an `import type` from a `.js` file to begin with, but whatever, I guess I know that now.
- Switching the `module` compiler flag to `node16` causes TS to no longer emit pure ESM code, so that's not happening, as emitting pure ESM only is what I want.
- This explicit imports problem is kinda recursive, just updating `tsex` in `watcher` doesn't fix it because there's another type "error" like that in a dependency that `watcher` imports, so I need to go over all my packages and update them all to totally fix this issue. 
- Also I was doing an unrelated [weird hack](https://github.com/fabiospampinato/tsex/commit/1fb59b1f3ce50ac497e9d80179d63746ce967bdd) in `tsex` to make sure I wouldn't have to specify source and output directories in every `tsconfig.json` of every package I maintain, but TS v5.5.0 incidentally added a template variable that addresses this issue properly, so that's another good reason to go over all my packages and update them anyway, I guess.

So yeah I need to go over these packages, hopefully I can get it done by tomorrow, it may take a little longer than that. In general I'd recommend putting `skipLibCheck: true` in your `tsconfig.json`, not using it is kinda unworkable imo, every non-patch release of TS could have breaking changes, one can't expect all dependencies to pass all checks in whatever arbitrary version of TS you are using.

**Comment by philkunz** [comment]
I'm not sure I follow. Isn't TypeScript exactly for having type safety? Doesn't TypeScript do everything correctly out of the box? I also built a bunch of ts convenience packages: https://code.foss.global/git.zone

I rarely have any problems with TypeScript. Its only around the change to esm that people often get stuff mixed up. Also, it is a lot cleaner to work with `"verbatimModuleSyntax": true`, so `type` imports become a thing.

With the latest node + typescript combo, you can even completely skip cjs while not upsetting people that use require: https://joyeecheung.github.io/blog/2024/03/18/require-esm-in-node-js/

**Comment by benmccann** [comment]
> Switching the module compiler flag to node16 causes TS to no longer emit pure ESM code, so that's not happening, as emitting pure ESM only is what I want.

Oh, where is the output non-ESM with this flag? I hadn't noticed anything non-ESM with https://github.com/fabiospampinato/watcher/pull/38, but would be curious to learn more so I can keep an eye out for it in other projects I work on

**Comment by fabiospampinato** [comment]
> Oh, where is the output non-ESM with this flag?

Unfortunately I can no longer seem to be able to reproduce the issue 🙃 I don't know if I had done something wrong the other day or what.

---

This issue should be fixed by [this commit](https://github.com/fabiospampinato/watcher/commit/0ce0d063822db7f0db8a5eeae158edd77965329e) (and doing the same thing for everything `watcher` depends on). I'll double-check after I make a release before closing this issue.

**Comment by mnaoumov** [comment]
I can still reproduce the issue. Here is my patch for v2.3.1

```patch
diff --git a/node_modules/watcher/dist/types.d.ts b/node_modules/watcher/dist/types.d.ts
index 819f534..6fc41a4 100644
--- a/node_modules/watcher/dist/types.d.ts
+++ b/node_modules/watcher/dist/types.d.ts
@@ -1,8 +1,8 @@
 /// <reference types="node" />
 import type { FSWatcher, BigIntStats } from 'node:fs';
 import type { ResultDirectories } from 'tiny-readdir';
-import type { FSTargetEvent, TargetEvent } from './enums';
-import type WatcherStats from './watcher_stats';
+import type { FSTargetEvent, TargetEvent } from './enums.d.ts';
+import type WatcherStats from './watcher_stats.d.ts';
 type Callback = () => void;
 type Disposer = () => void;
 type Event = [TargetEvent, Path, Path?];
diff --git a/node_modules/watcher/dist/utils.d.ts b/node_modules/watcher/dist/utils.d.ts
index 04221a1..027688f 100644
--- a/node_modules/watcher/dist/utils.d.ts
+++ b/node_modules/watcher/dist/utils.d.ts
@@ -3,7 +3,7 @@
 /// <reference types="node" />
 /// <reference types="node" />
 /// <reference types="node" />
-import type { Callback, Ignore, ReaddirMap, Stats } from './types';
+import type { Callback, Ignore, ReaddirMap, Stats } from './types.d.ts';
 declare const Utils: {
     lang: {
         debounce: <Args extends unknown[]>(fn: import("dettle/dist/types").FN<Args, unknown>, wait?: number | undefined, options?: import("dettle/dist/types").DebounceOptions | undefined) => import("dettle/dist/types").Debounced<Args>;
diff --git a/node_modules/watcher/dist/watcher.d.ts b/node_modules/watcher/dist/watcher.d.ts
index 352c3c2..1dd89d1 100644
--- a/node_modules/watcher/dist/watcher.d.ts
+++ b/node_modules/watcher/dist/watcher.d.ts
@@ -1,11 +1,11 @@
 /// <reference types="node" />
 /// <reference types="node" />
 import { EventEmitter } from 'node:events';
-import { TargetEvent } from './enums';
-import WatcherHandler from './watcher_handler';
-import WatcherLocker from './watcher_locker';
-import WatcherPoller from './watcher_poller';
-import type { Callback, Disposer, Handler, Ignore, Path, PollerConfig, SubwatcherConfig, WatcherOptions, WatcherConfig } from './types';
+import type { TargetEvent } from './enums.d.ts';
+import type WatcherHandler from './watcher_handler.d.ts';
+import type WatcherLocker from './watcher_locker.d.ts';
+import type WatcherPoller from './watcher_poller.d.ts';
+import type { Callback, Disposer, Handler, Ignore, Path, PollerConfig, SubwatcherConfig, WatcherOptions, WatcherConfig } from './types.d.ts';
 declare class Watcher extends EventEmitter {
     _closed: boolean;
     _ready: boolean;
diff --git a/node_modules/watcher/dist/watcher_handler.d.ts b/node_modules/watcher/dist/watcher_handler.d.ts
index b92ac0a..e9d3668 100644
--- a/node_modules/watcher/dist/watcher_handler.d.ts
+++ b/node_modules/watcher/dist/watcher_handler.d.ts
@@ -1,8 +1,8 @@
 /// <reference types="node" />
 /// <reference types="node" />
-import { FSTargetEvent } from './enums';
-import type Watcher from './watcher';
-import type { Event, FSWatcher, Handler, HandlerBatched, Path, WatcherOptions, WatcherConfig } from './types';
+import type { FSTargetEvent } from './enums.d.ts';
+import type Watcher from './watcher.d.ts';
+import type { Event, FSWatcher, Handler, HandlerBatched, Path, WatcherOptions, WatcherConfig } from './types.d.ts';
 declare class WatcherHandler {
     base?: WatcherHandler;
     watcher: Watcher;
diff --git a/node_modules/watcher/dist/watcher_locker.d.ts b/node_modules/watcher/dist/watcher_locker.d.ts
index 4b948a5..10dd3a1 100644
--- a/node_modules/watcher/dist/watcher_locker.d.ts
+++ b/node_modules/watcher/dist/watcher_locker.d.ts
@@ -1,6 +1,6 @@
-import { TargetEvent } from './enums';
-import type Watcher from './watcher';
-import type { Path, LocksAdd, LocksUnlink, LocksPair, LockConfig } from './types';
+import type { TargetEvent } from './enums.d.ts';
+import type Watcher from './watcher.d.ts';
+import type { Path, LocksAdd, LocksUnlink, LocksPair, LockConfig } from './types.d.ts';
 declare class WatcherLocker {
     _locksAdd: LocksAdd;
     _locksAddDir: LocksAdd;
diff --git a/node_modules/watcher/dist/watcher_poller.d.ts b/node_modules/watcher/dist/watcher_poller.d.ts
index ed1263f..d32b230 100644
--- a/node_modules/watcher/dist/watcher_poller.d.ts
+++ b/node_modules/watcher/dist/watcher_poller.d.ts
@@ -1,7 +1,7 @@
-import { FileType, TargetEvent } from './enums';
-import LazyMapSet from './lazy_map_set';
-import WatcherStats from './watcher_stats';
-import type { INO, Path } from './types';
+import type { FileType, TargetEvent } from './enums.d.ts';
+import type LazyMapSet from './lazy_map_set.d.ts';
+import type WatcherStats from './watcher_stats.d.ts';
+import type { INO, Path } from './types.d.ts';
 declare class WatcherPoller {
     inos: Partial<Record<TargetEvent, Record<Path, [INO, FileType]>>>;
     paths: LazyMapSet<INO, Path>;
diff --git a/node_modules/watcher/dist/watcher_stats.d.ts b/node_modules/watcher/dist/watcher_stats.d.ts
index 6173303..fb7bd4c 100644
--- a/node_modules/watcher/dist/watcher_stats.d.ts
+++ b/node_modules/watcher/dist/watcher_stats.d.ts
@@ -1,4 +1,4 @@
-import type { INO, Stats } from './types';
+import type { INO, Stats } from './types.d.ts';
 declare class WatcherStats {
     ino: INO;
     size: number;
diff --git a/node_modules/watcher/src/constants.ts b/node_modules/watcher/src/constants.ts
index c3a1804..92c2803 100644
--- a/node_modules/watcher/src/constants.ts
+++ b/node_modules/watcher/src/constants.ts
@@ -1,7 +1,7 @@
 
 /* IMPORT */
 
-import os from 'node:os';
+import * as os from 'node:os';
 
 /* MAIN */
 
diff --git a/node_modules/watcher/src/utils.ts b/node_modules/watcher/src/utils.ts
index 901638b..88f50d2 100644
--- a/node_modules/watcher/src/utils.ts
+++ b/node_modules/watcher/src/utils.ts
@@ -2,8 +2,8 @@
 /* IMPORT */
 
 import {debounce} from 'dettle';
-import fs from 'node:fs';
-import path from 'node:path';
+import * as fs from 'node:fs';
+import * as path from 'node:path';
 import sfs from 'stubborn-fs';
 import readdir from 'tiny-readdir';
 import {POLLING_TIMEOUT} from './constants';
diff --git a/node_modules/watcher/src/watcher.ts b/node_modules/watcher/src/watcher.ts
index 8638414..f141db3 100644
--- a/node_modules/watcher/src/watcher.ts
+++ b/node_modules/watcher/src/watcher.ts
@@ -2,8 +2,8 @@
 /* IMPORT */
 
 import {EventEmitter} from 'node:events';
-import fs from 'node:fs';
-import path from 'node:path';
+import * as fs from 'node:fs';
+import * as path from 'node:path';
 import {DEPTH, LIMIT, HAS_NATIVE_RECURSION, POLLING_INTERVAL} from './constants';
 import {TargetEvent, WatcherEvent} from './enums';
 import Utils from './utils';
@@ -128,7 +128,7 @@ class Watcher extends EventEmitter {
 
   pollerExists ( targetPath: Path, options: WatcherOptions ): boolean { //FIXME: This doesn't actually allow for multiple pollers to the same paths, but potentially in the future the same path could be polled with different callbacks to be called, which this doesn't currently allow for
 
-    for ( const poller of this._pollers ) {
+    for ( const poller of Array.from(this._pollers) ) {
 
       if ( poller.targetPath !== targetPath ) continue;
 
@@ -144,7 +144,7 @@ class Watcher extends EventEmitter {
 
   subwatcherExists ( targetPath: Path, options: WatcherOptions ): boolean { //FIXME: This doesn't actually allow for multiple subwatchers to the same paths, but potentially in the future the same path could be subwatched with different callbacks to be called, which this doesn't currently allow for
 
-    for ( const subwatcher of this._subwatchers ) {
+    for ( const subwatcher of Array.from(this._subwatchers) ) {
 
       if ( subwatcher.targetPath !== targetPath ) continue;
 
diff --git a/node_modules/watcher/src/watcher_handler.ts b/node_modules/watcher/src/watcher_handler.ts
index 5aa71d0..ad5bda1 100644
--- a/node_modules/watcher/src/watcher_handler.ts
+++ b/node_modules/watcher/src/watcher_handler.ts
@@ -1,7 +1,7 @@
 
 /* IMPORT */
 
-import path from 'node:path';
+import * as path from 'node:path';
 import {DEBOUNCE, DEPTH, LIMIT, HAS_NATIVE_RECURSION, IS_WINDOWS} from './constants';
 import {FSTargetEvent, FSWatcherEvent, TargetEvent} from './enums';
 import Utils from './utils';
@@ -66,7 +66,7 @@ class WatcherHandler {
       const flush = async ( initials: Event[], regulars: Set<Path> ): Promise<void> => {
 
         const initialEvents = this.options.ignoreInitial ? [] : initials;
-        const regularEvents = await this.eventsPopulate ([ ...regulars ]);
+        const regularEvents = await this.eventsPopulate (Array.from(regulars));
         const events = this.eventsDeduplicate ([ ...initialEvents, ...regularEvents ]);
 
         this.onTargetEvents ( events );
@@ -186,7 +186,7 @@ class WatcherHandler {
 
     if ( isInitial ) return events;
 
-    for ( const folderPathOther of this.watcher._poller.stats.keys () ) {
+    for ( const folderPathOther of Array.from(this.watcher._poller.stats.keys ()) ) {
 
       if ( !Utils.fs.isSubPath ( targetPath, folderPathOther ) ) continue;
 
diff --git a/node_modules/watcher/src/watcher_locks_resolver.ts b/node_modules/watcher/src/watcher_locks_resolver.ts
index f99838d..c2fc8a7 100644
--- a/node_modules/watcher/src/watcher_locks_resolver.ts
+++ b/node_modules/watcher/src/watcher_locks_resolver.ts
@@ -54,7 +54,7 @@ const WatcherLocksResolver = {
 
     const now = Date.now ();
 
-    for ( const [fn, timestamp] of WatcherLocksResolver.fns ) {
+    for ( const [fn, timestamp] of Array.from(WatcherLocksResolver.fns.entries()) ) {
 
       if ( timestamp >= now ) continue; // We should still wait some more for this
```
